name: cartographer
description: An app for making basic maps for games.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.13
  short_uuids: ^2.0.0

dev_dependencies:
  analyzer: ^4.0.0
  build_runner: ^2.1.10
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.6

flutter:
  uses-material-design: true
